# Generated by Django 5.1.3 on 2025-07-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_status_product_unit_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
