# Generated by Django 5.1.3 on 2025-07-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_cartitem_unit_productimage_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
